version: '3.8'

services:
  tracker:
    build:
      context: https://github.com/Makar-aka/retracker.git
      dockerfile: Dockerfile
    container_name: tracker
    restart: unless-stopped
    volumes:
      - ./config:/config:ro
      - ./data:/data
      - ./templates:/templates:ro
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"