version: '3.8'

services:
  tracker:
    build: .
    container_name: tracker
    restart: unless-stopped
    volumes:
      - ./config:/config:ro
      - ./data:/data
      - ./templates:/templates:ro
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"